[package]
name = "MARlea_simulator"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marlea_engine = "0.0.1"
structopt = "0.3"
